#!/bin/bash

# ============================================================================
# GLOBALS.SH - Global Variables and Constants
# ============================================================================

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[0;33m'
BLUE='\033[0;34m'
NC='\033[0m' # No Color

# Initialize global variables for the optimized flow
PLATFORM_TYPE=""
IS_JETSON=""
IS_DGX_SPARK=""
HAS_GPU=""
GPU_MODEL=""
GPU_FAMILY="unknown"
NVIDIA_DRIVER_VERSION=""
CONFIG_NAME=""
CONFIG_FILE=""
N8N_KEY_FILE="n8n_encryption_key.txt"
DETECTION_CHOICE=""
ACCESS_MODE="lan"  # Default to LAN mode
SYSTEM_HOSTNAME=""  # System hostname for LAN domain generation
K8S_CLUSTER_ACCESSIBLE=false  # Track if cluster is accessible
MIN_DGX_DRIVER_VERSION="590.44"

# NVIDIA driver policy for standard GPU platforms
MIN_NVIDIA_DRIVER_VERSION="570.26"

# Configuration file variables
USE_CONFIG_FILE=false
CONFIG_FILE_PATH=""
UPDATE_MODE=false
SKIP_CONFIG_IMPORT=false

# Resource variables
TOTAL_CPU=0
TOTAL_MEMORY_MB=0
K8S_CPU=0
K8S_MEMORY_MB=0
K8S_MEMORY_GB=0
K8S_CPU_FORMATTED=0
CLUSTER_AVAILABLE_STORAGE_GB=0
USABLE_STORAGE_GB=0
AVAILABLE_STORAGE_GB=0

# Cluster configuration variables
NODES_COUNT=0
LONGHORN_REPLICAS_COUNT=1

# Command variables
KUBECTL_CMD=""
HELM_CMD=""
HELM_STANDARD_AVAILABLE=false
HELM_MICROK8S_AVAILABLE=false
YAML_PARSER=""

# Component resource variables
CPU_OPENWEBUI=0
CPU_OLLAMA=0
CPU_N8N=0
CPU_N8N_WORKER=0
CPU_POSTGRES=0
CPU_REDIS=0
CPU_RUSTFS=0
CPU_COMFYUI=0

MEM_OPENWEBUI=0
MEM_OLLAMA=0
MEM_N8N=0
MEM_N8N_WORKER=0
MEM_POSTGRES=0
MEM_REDIS=0
MEM_RUSTFS=0
MEM_COMFYUI=0

# Request resources (calculated as 50% of limits)
CPU_OPENWEBUI_REQ=0
CPU_OLLAMA_REQ=0
CPU_N8N_REQ=0
CPU_N8N_WORKER_REQ=0
CPU_POSTGRES_REQ=0
CPU_REDIS_REQ=0
CPU_RUSTFS_REQ=0
CPU_COMFYUI_REQ=0

MEM_OPENWEBUI_REQ=0
MEM_OLLAMA_REQ=0
MEM_N8N_REQ=0
MEM_N8N_WORKER_REQ=0
MEM_POSTGRES_REQ=0
MEM_REDIS_REQ=0
MEM_RUSTFS_REQ=0
MEM_COMFYUI_REQ=0

# Configuration variables
CERT_EMAIL=""

# Network variables
PUBLIC_IP=""

# LAN access domains (.local)
ENABLE_LAN_ACCESS=""
ENABLE_LAN_TLS=""
OPENWEBUI_DOMAIN_LAN=""
N8N_DOMAIN_LAN=""
COMFYUI_DOMAIN_LAN=""
RUSTFS_DOMAIN_LAN=""
OLLAMA_DOMAIN_LAN=""

# Public access domains (internet)
ENABLE_PUBLIC_ACCESS=""
OPENWEBUI_DOMAIN_PUBLIC=""
N8N_DOMAIN_PUBLIC=""
COMFYUI_DOMAIN_PUBLIC=""
RUSTFS_DOMAIN_PUBLIC=""
OLLAMA_DOMAIN_PUBLIC=""

# Legacy single domain variables (for backward compatibility)
OPENWEBUI_DOMAIN=""
N8N_DOMAIN=""
COMFYUI_DOMAIN=""
RUSTFS_DOMAIN=""
OLLAMA_DOMAIN=""

# Storage variables
OPENWEBUI_STORAGE_SIZE=""
OLLAMA_STORAGE_SIZE=""
N8N_STORAGE_SIZE=""
PG_STORAGE_SIZE=""
REDIS_STORAGE_SIZE=""
RUSTFS_STORAGE_SIZE=""
COMFYUI_STORAGE_SIZE=""

OPENWEBUI_STORAGE_GB=""
OLLAMA_STORAGE_GB=""
N8N_STORAGE_GB=""
PG_STORAGE_GB=""
REDIS_STORAGE_GB=""
RUSTFS_STORAGE_GB=""
COMFYUI_STORAGE_GB=""

# OpenWebUI SSO Configuration
ENABLE_OPENWEBUI_SSO=""
OPENWEBUI_SSO_PROVIDER=""
OPENWEBUI_OAUTH_CLIENT_ID=""
OPENWEBUI_OAUTH_CLIENT_SECRET=""
OPENWEBUI_OAUTH_PROVIDER_NAME=""
OPENWEBUI_OAUTH_SCOPES=""
OPENWEBUI_OPENID_PROVIDER_URL=""
OPENWEBUI_OPENID_REDIRECT_URI=""
OPENWEBUI_GOOGLE_CLIENT_ID=""
OPENWEBUI_GOOGLE_CLIENT_SECRET=""
OPENWEBUI_GOOGLE_REDIRECT_URI=""
OPENWEBUI_MICROSOFT_CLIENT_ID=""
OPENWEBUI_MICROSOFT_CLIENT_SECRET=""
OPENWEBUI_MICROSOFT_CLIENT_TENANT_ID=""
OPENWEBUI_MICROSOFT_REDIRECT_URI=""
OPENWEBUI_GITHUB_CLIENT_ID=""
OPENWEBUI_GITHUB_CLIENT_SECRET=""
OPENWEBUI_TRUSTED_EMAIL_HEADER=""
OPENWEBUI_TRUSTED_NAME_HEADER=""
ENABLE_OPENWEBUI_OAUTH_SIGNUP=""
ENABLE_OPENWEBUI_OAUTH_MERGE_ACCOUNTS=""
ENABLE_OPENWEBUI_OAUTH_UPDATE_PICTURE=""

# Component configuration
ENABLE_RUSTFS=""
RUSTFS_ROOT_USER=""
RUSTFS_ROOT_PASSWORD=""
ENABLE_COMFYUI=""
COMFYUI_IMAGE=""
COMFYUI_LOW_VRAM=""
COMFYUI_MODELS_DOWNLOAD=""
COMFYUI_AUTH_USER=""
COMFYUI_AUTH_HASH=""
OLLAMA_IMAGE=""
VRAM_PERCENTAGE=""
OLLAMA_GPU_ENABLED=""

# N8N configuration
N8N_KEY=""
N8N_WORKER_REPLICAS=1
ENABLE_N8N_SMTP=""
N8N_SMTP_HOST=""
N8N_SMTP_PORT=""
N8N_SMTP_USER=""
N8N_SMTP_PASS=""
N8N_SMTP_SENDER=""
N8N_SMTP_SSL=""
N8N_SMTP_STARTTLS=""
N8N_ADMIN_EMAIL=""
N8N_ADMIN_PASSWORD=""
N8N_ADMIN_FIRST_NAME=""
N8N_ADMIN_LAST_NAME=""

# Deployment configuration
NAMESPACE="lair"
RELEASE_NAME=""
NEW_INSTALL=""
AUTO_DEPLOY=""
CREATE_STORAGE_CLASS_ENABLED=""
STORAGE_CLASS_NAME=""
CREATE_CLUSTER_ISSUER=""

# Minimum values for requests
MIN_CPU_REQ=10 # 10m
MIN_MEM_REQ=16 # 16Mi

# Percentage of system resources to allocate to Kubernetes for requests (overcommitment strategy)
K8S_RESOURCE_ALLOCATION_PERCENTAGE=52

# Percentage of available storage to actually use for Lair (safety factor)
STORAGE_SAFETY_PERCENTAGE=80

# Resource allocation percentages (automatic)
PERCENTAGE_OPENWEBUI=25
PERCENTAGE_OLLAMA=35
PERCENTAGE_N8N=5
PERCENTAGE_REDIS=3
PERCENTAGE_POSTGRES=5
PERCENTAGE_RUSTFS=7
PERCENTAGE_COMFYUI=20

# Limit multipliers for overcommit (how much more than requests can be used for burst)
# These are intentionally high to allow apps to burst when others are idle.
LIMIT_MULTIPLIER_OPENWEBUI=4.0    # Web UI can burst 4x for user interactions
LIMIT_MULTIPLIER_OLLAMA=3.5       # AI inference can burst 3.5x for model loading
LIMIT_MULTIPLIER_N8N=3.0          # Workflow automation can burst 3x for complex workflows
LIMIT_MULTIPLIER_REDIS=3.0        # Cache can burst 3x for heavy operations
LIMIT_MULTIPLIER_POSTGRES=3.0     # Database can burst 3x for queries
LIMIT_MULTIPLIER_RUSTFS=3.5        # Object storage can burst 3.5x for I/O operations
LIMIT_MULTIPLIER_COMFYUI=6.0      # AI generation can burst 4x for rendering

# Component-specific minimum requirements (in millicore for CPU, MB for memory)
# These are ABSOLUTE minimums for each component to function properly
MIN_CPU_OPENWEBUI=500      # 500m - web interface needs responsive CPU
MIN_MEM_OPENWEBUI=1024     # 1GB - web app with caching

MIN_CPU_OLLAMA=1000        # 1000m - AI inference needs substantial CPU
MIN_MEM_OLLAMA=2048        # 2GB - model loading and inference

MIN_CPU_COMFYUI=1000       # 1000m - AI generation requires substantial CPU even in CPU mode
MIN_MEM_COMFYUI=2048       # 2GB - ComfyUI needs memory for image processing and models

MIN_CPU_N8N=200            # 200m - workflow automation
MIN_MEM_N8N=512            # 512MB - moderate memory for workflows

MIN_CPU_POSTGRES=100       # 100m - database can run on less CPU
MIN_MEM_POSTGRES=256       # 256MB - database minimum

MIN_CPU_REDIS=100          # 100m - cache/queue service
MIN_MEM_REDIS=128          # 128MB - in-memory cache

MIN_CPU_RUSTFS=200          # 200m - object storage I/O
MIN_MEM_RUSTFS=512          # 512MB - object storage operations

# Tika is always deployed and is not part of the component percentage split.
CPU_TIKA=1500
MEM_TIKA=1536
CPU_TIKA_REQ=100
MEM_TIKA_REQ=256

# Export all variables to make them available to other modules
export RED GREEN YELLOW BLUE NC
export PLATFORM_TYPE IS_JETSON IS_DGX_SPARK HAS_GPU GPU_MODEL NVIDIA_DRIVER_VERSION CONFIG_NAME CONFIG_FILE N8N_KEY_FILE DETECTION_CHOICE ACCESS_MODE SYSTEM_HOSTNAME K8S_CLUSTER_ACCESSIBLE
export MIN_DGX_DRIVER_VERSION
export USE_CONFIG_FILE CONFIG_FILE_PATH
export TOTAL_CPU TOTAL_MEMORY_MB K8S_CPU K8S_MEMORY_MB K8S_MEMORY_GB K8S_CPU_FORMATTED CLUSTER_AVAILABLE_STORAGE_GB USABLE_STORAGE_GB AVAILABLE_STORAGE_GB
export NODES_COUNT LONGHORN_REPLICAS_COUNT
export KUBECTL_CMD HELM_CMD YAML_PARSER
export CPU_OPENWEBUI CPU_OLLAMA CPU_N8N CPU_N8N_WORKER CPU_POSTGRES CPU_REDIS CPU_RUSTFS CPU_COMFYUI
export MEM_OPENWEBUI MEM_OLLAMA MEM_N8N MEM_N8N_WORKER MEM_POSTGRES MEM_REDIS MEM_RUSTFS MEM_COMFYUI
export CPU_OPENWEBUI_REQ CPU_OLLAMA_REQ CPU_N8N_REQ CPU_N8N_WORKER_REQ CPU_POSTGRES_REQ CPU_REDIS_REQ CPU_RUSTFS_REQ CPU_COMFYUI_REQ
export MEM_OPENWEBUI_REQ MEM_OLLAMA_REQ MEM_N8N_REQ MEM_N8N_WORKER_REQ MEM_POSTGRES_REQ MEM_REDIS_REQ MEM_RUSTFS_REQ MEM_COMFYUI_REQ
export CERT_EMAIL ENABLE_LAN_ACCESS ENABLE_LAN_TLS ENABLE_PUBLIC_ACCESS
export OPENWEBUI_DOMAIN_LAN N8N_DOMAIN_LAN COMFYUI_DOMAIN_LAN RUSTFS_DOMAIN_LAN OLLAMA_DOMAIN_LAN
export OPENWEBUI_DOMAIN_PUBLIC N8N_DOMAIN_PUBLIC COMFYUI_DOMAIN_PUBLIC RUSTFS_DOMAIN_PUBLIC OLLAMA_DOMAIN_PUBLIC
export OPENWEBUI_DOMAIN N8N_DOMAIN COMFYUI_DOMAIN RUSTFS_DOMAIN OLLAMA_DOMAIN
export OPENWEBUI_STORAGE_SIZE OLLAMA_STORAGE_SIZE N8N_STORAGE_SIZE PG_STORAGE_SIZE REDIS_STORAGE_SIZE RUSTFS_STORAGE_SIZE COMFYUI_STORAGE_SIZE
export OPENWEBUI_STORAGE_GB OLLAMA_STORAGE_GB N8N_STORAGE_GB PG_STORAGE_GB REDIS_STORAGE_GB RUSTFS_STORAGE_GB COMFYUI_STORAGE_GB
export ENABLE_OPENWEBUI_SSO OPENWEBUI_SSO_PROVIDER OPENWEBUI_OAUTH_CLIENT_ID OPENWEBUI_OAUTH_CLIENT_SECRET OPENWEBUI_OAUTH_PROVIDER_NAME OPENWEBUI_OAUTH_SCOPES OPENWEBUI_OPENID_PROVIDER_URL OPENWEBUI_OPENID_REDIRECT_URI
export OPENWEBUI_GOOGLE_CLIENT_ID OPENWEBUI_GOOGLE_CLIENT_SECRET OPENWEBUI_GOOGLE_REDIRECT_URI OPENWEBUI_MICROSOFT_CLIENT_ID OPENWEBUI_MICROSOFT_CLIENT_SECRET OPENWEBUI_MICROSOFT_CLIENT_TENANT_ID OPENWEBUI_MICROSOFT_REDIRECT_URI
export OPENWEBUI_GITHUB_CLIENT_ID OPENWEBUI_GITHUB_CLIENT_SECRET OPENWEBUI_TRUSTED_EMAIL_HEADER OPENWEBUI_TRUSTED_NAME_HEADER ENABLE_OPENWEBUI_OAUTH_SIGNUP ENABLE_OPENWEBUI_OAUTH_MERGE_ACCOUNTS ENABLE_OPENWEBUI_OAUTH_UPDATE_PICTURE
export ENABLE_RUSTFS RUSTFS_ROOT_USER RUSTFS_ROOT_PASSWORD ENABLE_COMFYUI COMFYUI_IMAGE COMFYUI_LOW_VRAM COMFYUI_MODELS_DOWNLOAD COMFYUI_AUTH_USER COMFYUI_AUTH_HASH OLLAMA_IMAGE VRAM_PERCENTAGE OLLAMA_GPU_ENABLED
export N8N_KEY N8N_WORKER_REPLICAS ENABLE_N8N_SMTP N8N_SMTP_HOST N8N_SMTP_PORT N8N_SMTP_USER N8N_SMTP_PASS N8N_SMTP_SENDER N8N_SMTP_SSL N8N_SMTP_STARTTLS N8N_ADMIN_EMAIL N8N_ADMIN_PASSWORD N8N_ADMIN_FIRST_NAME N8N_ADMIN_LAST_NAME
export NAMESPACE RELEASE_NAME NEW_INSTALL AUTO_DEPLOY CREATE_STORAGE_CLASS_ENABLED STORAGE_CLASS_NAME CREATE_CLUSTER_ISSUER
export MIN_CPU_REQ MIN_MEM_REQ
export K8S_RESOURCE_ALLOCATION_PERCENTAGE
export STORAGE_SAFETY_PERCENTAGE
export PERCENTAGE_OPENWEBUI PERCENTAGE_OLLAMA PERCENTAGE_N8N PERCENTAGE_REDIS PERCENTAGE_POSTGRES PERCENTAGE_RUSTFS PERCENTAGE_COMFYUI
export LIMIT_MULTIPLIER_OPENWEBUI LIMIT_MULTIPLIER_OLLAMA LIMIT_MULTIPLIER_N8N LIMIT_MULTIPLIER_REDIS LIMIT_MULTIPLIER_POSTGRES LIMIT_MULTIPLIER_RUSTFS LIMIT_MULTIPLIER_COMFYUI
export MIN_CPU_OPENWEBUI MIN_MEM_OPENWEBUI
export MIN_CPU_OLLAMA MIN_MEM_OLLAMA
export MIN_CPU_COMFYUI MIN_MEM_COMFYUI
export MIN_CPU_N8N MIN_MEM_N8N
export MIN_CPU_POSTGRES MIN_MEM_POSTGRES
export MIN_CPU_REDIS MIN_MEM_REDIS
export MIN_CPU_RUSTFS MIN_MEM_RUSTFS
export CPU_TIKA MEM_TIKA CPU_TIKA_REQ MEM_TIKA_REQ
